/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 11-Jan-2018 9:21:05 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

USE `am_file_manager`
;

SET FOREIGN_KEY_CHECKS=0 
;

/* Create Tables */

CREATE TABLE `actual_file`
(
	`actual_file_id` INT NOT NULL AUTO_INCREMENT,
	`file_name` VARCHAR(150) NOT NULL,
	`extension` VARCHAR(10) NOT NULL,
	`server_file_path` VARCHAR(300) NOT NULL,
	`file_size` INT NOT NULL,
	`num_of_requests` INT NOT NULL,
	`is_uploaded` BOOL NOT NULL,
	`drive_file_url` VARCHAR(300) NOT NULL,
	CONSTRAINT `PK_actual_file` PRIMARY KEY (`actual_file_id` ASC)
)

;

CREATE TABLE `google_drive_accounts`
(
	`account_id` INT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(100) NOT NULL,
	`password` VARCHAR(100) NOT NULL,
	`free_size` INT NOT NULL,
	`creation_date` DATETIME NOT NULL,
	`full_size_date` DATETIME NOT NULL,
	`num_of_files` INT NOT NULL,
	CONSTRAINT `PK_google_drive_accounts` PRIMARY KEY (`account_id` ASC)
)

;

CREATE TABLE `uploaded_files`
(
	`uploaded_file_id` INT NOT NULL AUTO_INCREMENT,
	`actual_file_id` INT NOT NULL,
	`drive_account_id` INT NOT NULL,
	`drive_file_url` VARCHAR(300) NOT NULL,
	`upload_date` VARCHAR(50) 	,
	`uploading_time` VARCHAR(50) 	,
	`upload_start_date` DATETIME NOT NULL,
	`upload_end_date` DATETIME NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`uploaded_file_id` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `uploaded_files` 
 ADD CONSTRAINT `FK_uploaded_files_actual_file`
	FOREIGN KEY (`actual_file_id`) REFERENCES `actual_file` (`actual_file_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `uploaded_files` 
 ADD CONSTRAINT `FK_uploaded_files_google_drive_accounts`
	FOREIGN KEY (`drive_account_id`) REFERENCES `google_drive_accounts` (`account_id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
