/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Jan-2018 4:52:59 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Create Tables */

CREATE TABLE `event`
(
	`event_id` INT NOT NULL AUTO_INCREMENT,
	`event_type` VARCHAR(5) NOT NULL,
	`category_related_id` VARCHAR(50) NOT NULL,
	`creation_date` DATETIME NOT NULL,
	`is_completed` BOOL 	,
	`completion_date` DATETIME 	,
	CONSTRAINT `PK_notification` PRIMARY KEY (`event_id` ASC)
)

;

CREATE TABLE `event_category`
(
	`category` VARCHAR(3) NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_notification_category` PRIMARY KEY (`category` ASC)
)

;

CREATE TABLE `event_notification`
(
	`event_notif_id` VARCHAR(10) NOT NULL,
	`event_type` VARCHAR(5) NOT NULL,
	`notification` VARCHAR(5) NOT NULL,
	`description` VARCHAR(200) NOT NULL,
	CONSTRAINT `PK_event_notification` PRIMARY KEY (`event_notif_id` ASC)
)

;

CREATE TABLE `event_parameter`
(
	`parameter_id` INT NOT NULL AUTO_INCREMENT,
	`event_id` INT NOT NULL,
	`key` VARCHAR(50) NOT NULL,
	`value` TEXT NOT NULL,
	CONSTRAINT `PK_email_params` PRIMARY KEY (`parameter_id` ASC)
)

;

CREATE TABLE `event_type`
(
	`type` VARCHAR(5) NOT NULL,
	`category` VARCHAR(2) NOT NULL,
	`description` VARCHAR(150) 	,
	CONSTRAINT `PK_event_type` PRIMARY KEY (`type` ASC)
)

;

CREATE TABLE `input_event`
(
	`event_id` INT NOT NULL AUTO_INCREMENT,
	`jms_id` VARCHAR(150) 	,
	`event_name` VARCHAR(10) 	,
	`category_related_id` VARCHAR(30) 	,
	`receive_date` DATETIME NOT NULL,
	`is_processed` BOOL 	,
	`failure_reason` TEXT 	,
	`num_of_trails` INT NOT NULL,
	`process_date` DATETIME 	,
	`is_valid` BOOL 	,
	`validation_date` DATETIME 	,
	CONSTRAINT `PK_input_event` PRIMARY KEY (`event_id` ASC)
)

;

CREATE TABLE `input_event_destination`
(
	`destination_id` INT NOT NULL AUTO_INCREMENT,
	`event_id` INT NOT NULL,
	`event_notification_id` VARCHAR(10) 	,
	`email` VARCHAR(60) 	,
	`phone` VARCHAR(20) 	,
	`user_id` VARCHAR(25) 	,
	`full_name` VARCHAR(50) 	,
	CONSTRAINT `PK_input_event_destination` PRIMARY KEY (`destination_id` ASC)
)

;

CREATE TABLE `input_event_parameter`
(
	`parameter_id` INT NOT NULL AUTO_INCREMENT,
	`event_id` INT NOT NULL,
	`key` VARCHAR(50) 	,
	`value` VARCHAR(200) 	,
	CONSTRAINT `PK_input_event_parameter` PRIMARY KEY (`parameter_id` ASC)
)

;

CREATE TABLE `java_mail_config`
(
	`mail_config_id` VARCHAR(10) NOT NULL,
	`smtp` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_java_mail_config` PRIMARY KEY (`mail_config_id` ASC)
)

;

CREATE TABLE `notification`
(
	`notification_id` INT NOT NULL AUTO_INCREMENT,
	`event_id` INT NOT NULL,
	`template_id` VARCHAR(15) NOT NULL,
	`full_message` LONGTEXT NOT NULL,
	`destination_address` VARCHAR(60) NOT NULL,
	`is_sent` BOOL 	,
	`sent_date` DATETIME 	,
	`sender_id` INT 	,
	`num_of_trails` INT 	,
	`failure_reason` TEXT 	,
	`full_name` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_email` PRIMARY KEY (`notification_id` ASC)
)

;

CREATE TABLE `notification_template`
(
	`notif_temp_id` VARCHAR(15) NOT NULL,
	`event_notif_id` VARCHAR(10) NOT NULL,
	`notification_type` VARCHAR(3) NOT NULL,
	`subject` VARCHAR(50) NOT NULL,
	`template_name` VARCHAR(100) NOT NULL,
	`num_of_placeholders` INT NOT NULL,
	CONSTRAINT `PK_email_templates` PRIMARY KEY (`notif_temp_id` ASC)
)

;

CREATE TABLE `notification_type`
(
	`type` VARCHAR(3) NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_notification_type` PRIMARY KEY (`type` ASC)
)

;

CREATE TABLE `system_address`
(
	`address_id` INT NOT NULL AUTO_INCREMENT,
	`address` VARCHAR(60) NOT NULL,
	`type` VARCHAR(3) NOT NULL,
	`address_password` VARCHAR(50) NOT NULL,
	`mail_config_id` VARCHAR(10) NOT NULL,
	CONSTRAINT `PK_system_address` PRIMARY KEY (`address_id` ASC)
)

;

CREATE TABLE `users`
(
	`username` VARCHAR(50) NOT NULL,
	`password` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_users` PRIMARY KEY (`username` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `event` 
 ADD CONSTRAINT `FK_event_event_type`
	FOREIGN KEY (`event_type`) REFERENCES `event_type` (`type`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `event_notification` 
 ADD CONSTRAINT `FK_event_notification_event_type`
	FOREIGN KEY (`event_type`) REFERENCES `event_type` (`type`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `event_parameter` 
 ADD CONSTRAINT `FK_event_parameter_event`
	FOREIGN KEY (`event_id`) REFERENCES `event` (`event_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `event_type` 
 ADD CONSTRAINT `FK_event_type_event_category`
	FOREIGN KEY (`category`) REFERENCES `event_category` (`category`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `input_event_destination` 
 ADD CONSTRAINT `FK_input_event_destination_input_event`
	FOREIGN KEY (`event_id`) REFERENCES `input_event` (`event_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `input_event_parameter` 
 ADD CONSTRAINT `FK_input_event_parameter_input_event`
	FOREIGN KEY (`event_id`) REFERENCES `input_event` (`event_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `notification` 
 ADD CONSTRAINT `FK_notification_event`
	FOREIGN KEY (`event_id`) REFERENCES `event` (`event_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `notification` 
 ADD CONSTRAINT `FK_notification_notification_template`
	FOREIGN KEY (`template_id`) REFERENCES `notification_template` (`notif_temp_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `notification` 
 ADD CONSTRAINT `FK_notification_system_address`
	FOREIGN KEY (`sender_id`) REFERENCES `system_address` (`address_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `notification_template` 
 ADD CONSTRAINT `FK_notification_template_event_notification`
	FOREIGN KEY (`event_notif_id`) REFERENCES `event_notification` (`event_notif_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `notification_template` 
 ADD CONSTRAINT `FK_notification_template_notification_type`
	FOREIGN KEY (`notification_type`) REFERENCES `notification_type` (`type`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `system_address` 
 ADD CONSTRAINT `FK_system_address_java_mail_config`
	FOREIGN KEY (`mail_config_id`) REFERENCES `java_mail_config` (`mail_config_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `system_address` 
 ADD CONSTRAINT `FK_system_address_notification_type`
	FOREIGN KEY (`type`) REFERENCES `notification_type` (`type`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
